Dimmer Parameter Naming Changes
zwave_js_server.exceptions.NotFoundError: Configuration parameter with parameter name LED Effect Type could not be found

Z-Wave JS to MQTT container 6.7.4 (server 9.0.4) has been updated with a new configuration file for Inovelli dimmers.  Logic is the same.  This seems to have worked with 6.7.3 and below.  I expect the switch and combo fan / lights will be next.